# Initialization commands
/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh true
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate
# /vis/scene/add/axes 0 0 0 1 m

# Visualization of tokamak components

# Plasma
# /vis/geometry/set/colour name depth R G B opacity
/vis/geometry/set/forceSolid logicPlasma 1 1
/vis/geometry/set/colour logicPlasma 1 1 0 0 0.2

# Central solenoid
/vis/geometry/set/forceSolid logicCS 1 1
/vis/geometry/set/colour logicCS 1 0.6 0.5 0.5 1

# 1st wall
/vis/geometry/set/forceSolid logicWall_1 1 1
/vis/geometry/set/colour logicWall_1 1 0.3 0.3 0.3 1

# 1st wall heat sink (CuCrZr, reddish)
/vis/geometry/set/forceSolid logicWall_1_HeatSink 1 1
/vis/geometry/set/colour logicWall_1_HeatSink 1 0.5 0.1 0.1 1

# BLK breeder (blue-ish)
/vis/geometry/set/forceSolid logicBLK_breeder 1 1
/vis/geometry/set/colour logicBLK_breeder 1 0.3 0.5 0.5 1

# BLK support
/vis/geometry/set/forceSolid logicBLK_support 1 1
/vis/geometry/set/colour logicBLK_support 1 0.4 0.3 0.3 1

# Toroidal Field Coils (TFC)
#/vis/geometry/set/forceSolid logicTFC 1 1
#/vis/geometry/set/colour logicTFC 1 0.5 0.5 0.5 1

# TFCi
/vis/geometry/set/forceSolid logicTFCi 1 1
/vis/geometry/set/colour logicTFCi 1 0.5 0.5 0.5 1

# Vacuum Vessel (VV)
/vis/geometry/set/forceSolid logicVV 1 1
/vis/geometry/set/colour logicVV 1 0.9 0.9 0.9 1

# Filling
/vis/geometry/set/forceSolid logicFilling 1 1
/vis/geometry/set/colour logicFilling 1 0.6 0.6 0.6 1

# Bioshield
/vis/geometry/set/forceSolid logicBioshield_lat 1 1
/vis/geometry/set/colour logicBioshield_lat 1 0.4 0.4 0.4 1
/vis/geometry/set/forceSolid logicBioshield_updown 1 1
/vis/geometry/set/colour logicBioshield_updown 1 0.4 0.4 0.4 1

# Cryostat
/vis/geometry/set/forceSolid logicCryostat 1 1
/vis/geometry/set/colour logicCryostat 1 0.9 0.9 0.9 1
