# Initialization commands
/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh true
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate
# /vis/scene/add/axes 0 0 0 1 m

# Visualization of tokamak components

# Plasma
# /vis/geometry/set/colour name depth R G B opacity
/vis/geometry/set/forceSolid logicPlasma 1 1
/vis/geometry/set/colour logicPlasma 1 1 0 0 0.2

# Central solenoid
/vis/geometry/set/forceSolid logicCS 1 1
/vis/geometry/set/colour logicCS 1 0.7 0.5 0.5 1

# 1st wall
/vis/geometry/set/forceSolid logicWall_1 1 1
/vis/geometry/set/colour logicWall_1 1 0.3 0.3 0.3 1

# Toroidal Field Coils (TFC)
/vis/geometry/set/forceSolid logicTFC 1 1
/vis/geometry/set/colour logicTFC 1 0.6 0.6 0.6 1

## Vacuum Vessel (VV)
/vis/geometry/set/forceSolid logicVV 1 1
/vis/geometry/set/colour logicVV 1 0.9 0.9 0.9 1

## Bioshield
/vis/geometry/set/forceSolid logicBioshield 1 1
/vis/geometry/set/colour logicBioshield 1 0.4 0.4 0.4 0.5
/vis/geometry/set/forceSolid logicBioshield_up 1 1
/vis/geometry/set/colour logicBioshield_up 1 0.4 0.4 0.4 0.5
/vis/geometry/set/forceSolid logicBioshield_down 1 1
/vis/geometry/set/colour logicBioshield_down 1 0.4 0.4 0.4 0.5
