#include "Detector.hh"

MySensitiveDetector::MySensitiveDetector(G4String name) : G4VSensitiveDetector(name)
{
    N_Tritium = 0;
}

MySensitiveDetector::~MySensitiveDetector()
{}

// Return the number of Tritium atoms produced
G4int MySensitiveDetector::Get_Tritium() {
    return N_Tritium;
}

// Reset the number of Tritium atoms
void MySensitiveDetector::Reset_Tritium() {
    N_Tritium = 0;
}

// This method is used to COUNT the number of Tritium breeding reactions
// occurred. It does so by observing each particle: if it is a triton
// (tritium nucleus) and if ti was generated by a "neutronInelastic"
// process then a counter N_Tritium is increased.
G4bool MySensitiveDetector::ProcessHits(G4Step* aStep, G4TouchableHistory* ROhist)
{    
    
    G4String particle_name = aStep->GetTrack()->GetParticleDefinition()->GetParticleName();
    
    // Track of the current particle
    G4Track* track = aStep->GetTrack();
    
    // G4AnalysisManager* man = G4AnalysisManager::Instance();
    
    if(particle_name == "triton") {
        
        G4String creator_process = track->GetCreatorProcess()->GetProcessName();
        
        if(creator_process == "neutronInelastic") {
            
            ++N_Tritium;
                        
            // Kill the track: it's no longer useful because we've
            // already detected the Tritium breeding.
            track->SetTrackStatus(fStopAndKill);
        }
        
    } else if(particle_name != "neutron") {
        
        // Kill unnecessary tracks to save time and increase code speed
        track->SetTrackStatus(fStopAndKill);
    }
    
    
    return true;
}
